experimental: capture api for bullseye raspi
Idein/actfw-core pull request #57
Opened 2022-07-13 07:09 UTC by eguchi1904

## Check list

- [ ] I wrote [CHANGELOG.md](./CHANGELOG.md) if the pull request adds/modifies features.

## Summary

Camera capture api for bullseye raspberry Pi . This implementation is in early stages and API may change a lot in the future.

2022-07-14 06:10 UTC, ishiy1993 requested changes

2022-07-14 06:10 UTC, ishiy1993 commented on actfw_core/unicam_isp_capture.py
> +    def produceImageFromIsp(self) -> None:
Why use camelCase?

2022-07-14 06:10 UTC, ishiy1993 commented on actfw_core/unicam_isp_capture.py
> +    def adustSettingFromIsp(self) -> None:
Why use camelCase?

2022-07-14 09:10 UTC, ishiy1993 submitted a review, later dismissed
LGTM

2022-07-15 02:50 UTC, ishiy1993 approved these changes
LGTM

2022-07-19 02:56 UTC, KeenS approved these changes

2022-07-19 03:08 UTC, eguchi1904 commented
:pray::pray:

2022-07-19 03:08 UTC, merged