Initial implementation of camera contrast control
Idein/actfw-core pull request #64
Opened 2022-08-05 09:19 UTC by KeenS

## Check list

- [ ] I wrote [CHANGELOG.md](./CHANGELOG.md) if the pull request adds/modifies features.

## Summary
This patch provides initial implementation of contrast (gamma) control. This contains naive implementation of gamma and not contains `ce_enable` feature and reading config from files feature.

2022-08-18 08:08 UTC, KeenS commented on actfw_core/unicam_isp_capture.py
> +        # self.hi_max: int = 2000
following patch will use these variables

2022-08-18 08:49 UTC, ishiy1993 requested changes

2022-08-18 08:49 UTC, ishiy1993 commented on actfw_core/unicam_isp_capture.py
> +        contrast: Optional[float] = 1.0,
I think it's better to define `DEFAULT_CONTRAST = 1.0` and use it.

2022-08-18 08:49 UTC, ishiy1993 commented on actfw_core/unicam_isp_capture.py
> +        self.contrast: float = contrast or 1.0
use `DEFAULT_CONTRAST`.

2022-08-18 08:49 UTC, ishiy1993 commented on actfw_core/unicam_isp_capture.py
> +        self.do_contrast = not not contrast
```suggestion
        self.do_contrast = contrast is not None
```

2022-08-19 08:56 UTC, ishiy1993 approved these changes
LGTM

2022-08-19 08:58 UTC, merged